### ISSUE TITLE
Spline iCSD lower extend boundary

### ISSUE THREAD

**Issue by m-kowalska** [espenhgn/iCSD#5]
Hi, I'm Marta from Daniel's lab at Nencki. We're trying to compare iCSD methods to kCSD. I found a discrepancy in your Spline iCSD implementation. Could you please verify?

In file icsd.py at line 311, 426 and 474:

```
z_js = pl.zeros(el_len+2)
z_js[1:-1] = self.coord_electrode
z_js[-1] = z_js[-2] + pl.diff(self.coord_electrode).mean()
```

Here, I suspect that there must be the following line:
`z_js[0] = z_js[1] - pl.diff(self.coord_electrode).mean()`

Similarly in, line 386:
`coord_ext[0] = 0`
should be

```
coord_ext[0] =  self.coord_electrode[0] - \
            pl.diff(self.coord_electrode).mean()
```

Thanks!

**Comment by m-kowalska** [comment]
I see that this has been fixed in the dev branch. https://github.com/espenhgn/iCSD/blob/dev/icsd.py

**Comment by espenhgn** [comment]
Dear @m-kowalska,
Thanks for the heads-up. Yes, I hope this and other issues has been solved in the dev branch. Other issues I may merge from working on https://github.com/NeuralEnsemble/elephant/pull/55
