### ISSUE TITLE
matlab version? 

### ISSUE THREAD

**Issue by nsteinme** [espenhgn/iCSD#6]
The link to the original matlab version appears to be broken - do you know whether it is still hosted anywhere? Thanks -

**Comment by espenhgn** [comment]
Hi, 
I think the INCF code hosting was killed some time ago which took the matlab implementation with it. I dug up an old copy on an old computer, and now uploaded the codes here: https://github.com/espenhgn/CSDplotter 

But please understand that these codes are now 12 years old, and that you're probably better off with the iCSD methods either provided here or via the elephant project: https://github.com/NeuralEnsemble/elephant/

**Comment by nsteinme** [comment]
Excellent, thanks for doing that! Unfortunately I'm not on python... yet :)
